#!/usr/bin/env python3
"""Regenerate .preview/preview.html from ui/index.html + .preview/mock.js.

Why generate instead of hand-writing the harness: the first version carried its
own copy of index.html's markup. When a dialog gained a new control, the real UI
worked but the harness still had the old markup, so a scripted click threw and
the screenshot showed the un-opened dialog — a false negative that cost a whole
debug cycle. Generating the file keeps exactly one source of truth.

The generated file:
  * inserts <base href="../ui/"> so ./styles.css, ./js/*.js and ./assets/* resolve
    to the real workbench files;
  * inlines .preview/mock.js ahead of the workbench scripts (the stub must exist
    before the workbench boots).

The injection point deliberately does not name a script file — the workbench is
split across ui/js/*.js, and whichever file gets renamed or added next must not
break the harness. The anchor is picked, in order:
  1. the `<!-- app-scripts-anchor -->` marker in index.html;
  2. otherwise the last <script src=...> before </body>.
The stub is injected immediately before it, so it runs first.

Run:  python tools/make-preview.py
      (then open .preview/preview.html?theme=light&modal=retag )
"""

from __future__ import annotations

import json
import pathlib
import re
import sys

# The harness is imported for one side effect: a UTF-8 stdout/stderr. Windows
# consoles default to a legacy code page, and this tool prints non-ASCII.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import _harness  # noqa: E402,F401

ROOT = pathlib.Path(__file__).resolve().parent.parent
INDEX = ROOT / "ui" / "index.html"
MOCK = ROOT / ".preview" / "mock.js"
OUT = ROOT / ".preview" / "preview.html"

ANCHOR_COMMENT = "<!-- app-scripts-anchor -->"
SCRIPT_TAG = re.compile(r"[ \t]*<script\s+src=[^>]*>\s*\n?")


def injection_point(html: str) -> int:
    """Offset of the first workbench <script>, i.e. where the stub must go."""
    if ANCHOR_COMMENT in html:
        return html.index(ANCHOR_COMMENT)
    body = html.rindex("</body>") if "</body>" in html else len(html)
    tags = list(SCRIPT_TAG.finditer(html, 0, body))
    if not tags:
        return -1
    return tags[-1].start()


def main() -> int:
    for path in (INDEX, MOCK):
        if not path.exists():
            print(f"missing: {path}")
            return 1

    html = INDEX.read_text(encoding="utf-8")
    mock = MOCK.read_text(encoding="utf-8")

    # Hand the mock the manifest's version before it runs. The preview had a
    # hard-coded copy, so the About panel kept reporting 0.1.0 for several
    # releases — the same "a copy drifts" failure the arch badges had, where the
    # mock and the real code were wrong together and no test could see it.
    manifest = json.loads((ROOT / "manifest.json").read_text(encoding="utf-8"))
    mock = ("window.__IMREPO_MANIFEST__ = " + json.dumps(
        {"version": manifest.get("version", ""), "id": manifest.get("id", "")}) + ";\n") + mock

    at = injection_point(html)
    if at < 0:
        print(f"no workbench <script> tag found in {INDEX.name} (looked for "
              f"{ANCHOR_COMMENT} and for a <script src=...> before </body>)")
        return 1
    if "</script>" in mock:
        print("mock.js contains a literal </script>; it cannot be inlined as-is")
        return 1

    # 1. make the plugin's relative asset paths point at the real ui/ directory
    if '<base href="../ui/" />' not in html:
        marker = '<meta charset="UTF-8" />'
        if marker not in html:
            print("anchor not found: <meta charset>")
            return 1
        html = html.replace(marker, marker + '\n  <base href="../ui/" />', 1)

    # 2. inject the stub immediately before the first workbench script, so it
    #    has defined window.dbxPlugin by the time the workbench boots
    banner = (
        "<!-- GENERATED by tools/make-preview.py from ui/index.html + .preview/mock.js"
        " — do not edit by hand -->\n  "
    )
    html = html[:at] + banner + "<script>\n" + mock + "\n  </script>\n  " + html[at:]

    OUT.write_text(html, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(html):,} bytes, mock {len(mock):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
