#!/usr/bin/env python3
"""Regenerate .preview/preview.html from ui/index.html + .preview/mock.js.

Why generate instead of hand-writing the harness: the first version carried its
own copy of index.html's markup. When a dialog gained a new control, the real UI
worked but the harness still had the old markup, so a scripted click threw and
the screenshot showed the un-opened dialog — a false negative that cost a whole
debug cycle. Generating the file keeps exactly one source of truth.

The generated file:
  * inserts <base href="../ui/"> so ./styles.css, ./app.js and ./assets/* resolve
    to the real workbench files;
  * inlines .preview/mock.js ahead of app.js (the stub must exist before the
    workbench boots).

Run:  python tools/make-preview.py
      (then open .preview/preview.html?theme=light&modal=retag )
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
INDEX = ROOT / "ui" / "index.html"
MOCK = ROOT / ".preview" / "mock.js"
OUT = ROOT / ".preview" / "preview.html"

APP_TAG = '<script src="./app.js"></script>'


def main() -> int:
    for path in (INDEX, MOCK):
        if not path.exists():
            print(f"missing: {path}")
            return 1

    html = INDEX.read_text(encoding="utf-8")
    mock = MOCK.read_text(encoding="utf-8")

    if APP_TAG not in html:
        print(f"anchor not found in {INDEX.name}: {APP_TAG}")
        return 1
    if "</script>" in mock:
        print("mock.js contains a literal </script>; it cannot be inlined as-is")
        return 1

    # 1. make the plugin's relative asset paths point at the real ui/ directory
    if '<base href="../ui/" />' not in html:
        marker = '<meta charset="UTF-8" />'
        if marker not in html:
            print("anchor not found: <meta charset>")
            return 1
        html = html.replace(marker, marker + '\n  <base href="../ui/" />', 1)

    # 2. inject the stub so it runs before app.js
    banner = (
        "<!-- GENERATED by tools/make-preview.py from ui/index.html + .preview/mock.js"
        " — do not edit by hand -->\n  "
    )
    html = html.replace(APP_TAG, banner + "<script>\n" + mock + "\n  </script>\n  " + APP_TAG, 1)

    OUT.write_text(html, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(html):,} bytes, mock {len(mock):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
